### ISSUE TITLE
Question: evaluation?

### ISSUE THREAD

**Issue by tomek-he-him** [BaunCMS/Baun-Admin#6]
Hi, is it possible to evaluate the plugin without purchasing the license key?

We’re considering using Baun as one of many options for a commercial product. If it does prove well, we’ll definitely purchase a license. But without the possibility to test it out and see if it fits our needs we don’t want to risk spending money on any of the options. Even if there is a “no questions asked” refund.

**Comment by marksouthard** [comment]
The admin plugin is now open source and free for all to use.
